### ISSUE TITLE
Library uses DateTime instead of DateTimeOffset resulting in +1 hour data

### ISSUE THREAD

**Issue by aliostad** [openzipkin/zipkin4net#100]
Hi,

I normally use `DateTimeOffset` to ensure the real date never gets missed regardless of the local date. I see that `DateTime` gets used here and my guess was it just takes care of it but it seems it does not hence my traces are shown with +1 hour in zipkin.

Is there a design reason why `DateTime` gets used and not `DateTimeOffset`? I can send a PR but was wondering it could have another significance.

Thanks
Ali

**Comment by aliostad** [comment]
And funny thing is Zipkin UI says 20 minutes ago while it is 20 minutes in the future:

![image](https://user-images.githubusercontent.com/487334/28782936-a45d6fc4-7606-11e7-8ea5-1e47649397e5.png)
![image](https://user-images.githubusercontent.com/487334/28782965-bbdc61b4-7606-11e7-9146-9eb29e112f76.png)

**Comment by fedj** [comment]
UTC is used by default because we can have some servers on a different timezone. IMO, if you begin to use DateTimeOffset, you'll begin to get some serious problems in zipkin UI.
Shouldn't you set zipkin server to UTC ?

@adriancole Would you have a recommendation about that ?

**Comment by codefromthecrypt** [comment]
>
> @adriancole <https://github.com/adriancole> Would you have a
> recommendation about that ?
>
All libraries I've seen use UTC time (epoch millis or micros, a whole
number).  The server itself rarely uses time math, but when it does it sets
the TZ explicitly to UTC. For example, bucketing is based on midnight UTC.

javascript, may be another thing.. I think that's going to render based on
whatever the clock is on the browser in use.

main point is that all libraries, data and processing use UTC (epoch time,
millis or micros)

**Comment by codefromthecrypt** [comment]
ex. in our server code, we pin the clock to UTC so it isn't sensitive
to the host's timezone
https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch-http/src/main/java/zipkin/storage/elasticsearch/http/IndexNameFormatter.java#L59

**Comment by aliostad** [comment]
My point is the library does not enforce or constraint the DateTime to be UTC and using `DateTime` type, it is impossible to. The user of the library would not know if it needs to send UTC or just local DateTime.

All of this can be averted by making all the public interfaces to use `DateTimeOffset` so that within the library it gets changed to UTC (and in fact to microseconds before sending to zipkin).

Hope is clear.

**Comment by codefromthecrypt** [comment]
yeah much more clear.

FWIW most libraries don't actually pass things like DateTime around anyway
(rather numbers corresponding to epoch micros or a Clock facade that might
be backed by something like DateTime).

If DateTime cannot be coerced to UTC, then sounds like a bad choice, but I'll
leave it to y'all decide what to do.

**Comment by crntn** [comment]
@aliostad Thank you for the clarification, I agree that using DateTimeOffset for public interfaces would clear any doubt a client may have.  It would be a breaking change for the public API so we need to be careful. 
Short-term, since we don't serialize DateTime objects but rather an epoch utc  long, PR #102 should do it, would you agree ?

**Comment by aliostad** [comment]
Yeah, thanks I believe this should work. I am closing this issue.
