### ISSUE TITLE
Annotation constants such as cr, cs, etc not defined

### ISSUE THREAD

**Issue by aliostad** [openzipkin/zipkin4net#101]
Happy to chip in with a PR if you are OK.

**Comment by fedj** [comment]
Hi @aliostad,

Why would you need such constants ? Isn't trace.Record(Annotations.ClientRecv()) enough ?
Can you explain your use case ?

**Comment by aliostad** [comment]
Ah, I see. Yes, that suffice.

**Comment by aliostad** [comment]
Ah... is this correct?

I am trying to add an annotation but there is a type mismatch?

```
span.Annotations.Add(Annotations.ServerRecv());
```

> cannot convert from 'Criteo.Profiling.Tracing.Annotation.IAnnotation' to 'Criteo.Profiling.Tracing.Tracers.Zipkin.ZipkinAnnotation'

**Comment by fedj** [comment]
If you are trying to add an existing annotation to the span, the correct way to do it is trace.Record(Annotations.ServerRecv()).
If you're trying to add a custom annotation, then we'll need to discuss which one and how to do it.

**Comment by aliostad** [comment]
Frankly I do not understand the role of `Trace` here. I have a span, it has a public interface allowing me to add an annotation. The crux of the problem seem to be that the list has been defined as a list of `ZipkinAnnotation` and not `IAnnotation`.

In the part of code that I am trying to do this I have a span, not a trace. 

Again, I am a user of the library and I am trying to clear out things, I am happy to go along with the canonical suggestions of how to use the library. On the other hand, I have been a library developer for sometime and I can happily share some views on how to *let consumers fall into the pit of success*, if it is welcomed.

All in all, none of this is a criticism towards all the work that has been done here.

**Comment by crntn** [comment]
We definitely need to better document the role of Trace.cs as it is the cornerstone component when tracing your application. Usually  you don't manipulate directly Spans, their lifecycle is managed by [ZipkinTracer](https://github.com/criteo/zipkin4net/blob/master/zipkin4net/Criteo.Profiling.Tracing/Tracers/Zipkin/ZipkinTracer.cs).

It's interesting that your use case lead you to manipulate Spans directly, could you detail it ?
Also don't hesitate to share anything that you find confusing with the library, like you said the more instinctive the library is the better. 

For examples on how to use Trace, you can look at [ClientTrace](https://github.com/criteo/zipkin4net/blob/master/zipkin4net/Criteo.Profiling.Tracing/ClientTrace.cs) and [ServerTrace](https://github.com/criteo/zipkin4net/blob/master/zipkin4net/Criteo.Profiling.Tracing/ServerTrace.cs).

**Comment by fedj** [comment]
@aliostad Can we close this issue ?

**Comment by aliostad** [comment]
Sure, I guess another needed in terms of docs or approach.
