### ISSUE TITLE
Possibility to inject my HttpClient for HttpZipkinSender

### ISSUE THREAD

**Issue by klettier** [openzipkin/zipkin4net#104]
Hello,

I need to be able to send my **spans** to a secured instance of **Zipkin** and to do so link my authentication information to the POST request. 

I have two options

* Make a custom **IZipkinSender**
* Let me inject my custom **HttpClient** in [constructor](https://github.com/criteo/zipkin4net/blob/master/zipkin4net/Criteo.Profiling.Tracing/Transport/Http/HttpZipkinSender.cs#L18)

The second option seems better for me, what do you think ?

Regards,

kévin

**Comment by gboucher90** [comment]
Hello,

I would say changing the constructor from "internal" to "public" visibility would be more appropriate as it avoid code duplication on your side. I don't see any reasons not to do that.

**Comment by klettier** [comment]
Do you want a PR ?

**Comment by gboucher90** [comment]
If you can it would be great

**Comment by klettier** [comment]
Yeah no problem, should I include #106 ?

**Comment by gboucher90** [comment]
If you don't mind, could it be a separate PR for a cleaner "history" and discussions?

**Comment by klettier** [comment]
Yeah of course
