### ISSUE TITLE
Possible Memory leak

### ISSUE THREAD

**Issue by klettier** [openzipkin/zipkin4net#106]
Not disposed stream spotted [here](https://github.com/criteo/zipkin4net/blob/d1dbae9645f0d715b9e0b6cf58b20c2b1ac22faa/zipkin4net/Criteo.Profiling.Tracing/Tracers/Zipkin/ZipkinTracer.cs#L85)

Do you want a PR ?

**Comment by fedj** [comment]
@klettier, thanks for spotting this. I understand that disposable patterns should be called on Dispose method but here it's in fact not a problem since it's a local variable.
However, I understand that it would be clearer to explicit it. I would love a PR if you get the time to do it !

**Comment by klettier** [comment]
Thank you for your quick reply, I understand your point but as I could inject my proper **ISpanSerializer** that will be called with the non disposed MemoryStream it's a bit strange to consider it only as a local variable ?

**Comment by fedj** [comment]
Why do you need a custom ISpanSerializer? Is your format non-standard ?

Your point would be to reuse the memorystream accross multiple span serialization, right ?

**Comment by klettier** [comment]
My point is only to say that as long as this variable is shared across multiple objects it is not local at all. 
ZipkinTracer has the responsibility to manage the lifecycle of this variable and should dispose it as well. 

I will do the PR today, thank you again for your time.
