### ISSUE TITLE
Change repository layout

### ISSUE THREAD

**Issue by fedj** [openzipkin/zipkin4net#116]
Proposal:

 * Src
   * zipkin4net
     * Src
       * Contents of [Criteo.Profiling.Tracing](https://github.com/criteo/zipkin4net/tree/master/zipkin4net/Criteo.Profiling.Tracing)
     * Tests
       * Contents of [Criteo.Profiling.Tracing.UTest](https://github.com/criteo/zipkin4net/tree/master/zipkin4net/Criteo.Profiling.Tracing.UTest)
     * Benchmarks
       * Contents of [Criteo.Profiling.Tracing.Benchmark](https://github.com/criteo/zipkin4net/tree/master/zipkin4net/Criteo.Profiling.Tracing.Benchmark)
     * Solution file
   * zipkin4net.middleware.owin
     * Src
     * Tests
     * Solution file
   * zipkin4net.middleware.aspnetcore
     * Src
     * Solution file
 * Examples

**Comment by codefromthecrypt** [comment]
sgtm I guess these end up as different packages (to decouple dependencies)

**Comment by fedj** [comment]
Indeed, packages will remain seperated as it is today (one assembly per folder of Src)
