### ISSUE TITLE
Rethink build system

### ISSUE THREAD

**Issue by fedj** [openzipkin/zipkin4net#122]
Today, we have buildAndTest script duplicated almost everywhere. We need to find a build method that would be more efficient to read/write

**Comment by klettier** [comment]
My suggest would be to use [Fake](https://fake.build), I could make a code proposition if that's right for you

**Comment by fedj** [comment]
@klettier Thanks for the idea. To be fairly honest, I've never seen it in action and I have no idea how it would fit in the actual layout. How long would it be for you provide a sample for the main library (Src/zipkin4net) for example ?

**Comment by klettier** [comment]
It depends of what you expect, do you want CSharp script files as described [here](https://www.strathweb.com/2016/12/writing-c-build-scripts-with-fake-omnisharp-and-vs-code/) or [classic](https://fake.build/legacy-index.html#Simple-Example) FSharp script files ?

In either cases we should implement those tasks

* Clean 
* Build
* Test
* Pack

I will work on it today's evening and come back to you then.

**Comment by fedj** [comment]
Is there a big difference between both ? If not, I would rather stick with C# in order for everyone to understand it easily.

Otherwise, +1 on the tasks. Thanks a lot for your help and insight on this @klettier !

**Comment by codefromthecrypt** [comment]
indeed great and thanks for trying impactful ideas @klettier

**Comment by klettier** [comment]
[Here](https://github.com/criteo/zipkin4net/compare/master...klettier:feature/build?expand=1) is my proposition for the main library and [here](https://travis-ci.org/klettier/zipkin4net/builds/266457146) is the travis related build.

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target          Duration
------          --------
Clean           00:00:00.0082679
DotnetRestore   00:00:11.2961216
DotnetBuild     00:00:11.3137844
DotnetTest      00:00:08.7727046
DotnetPackage   Failure
Total:          00:00:32.9755281
---------------------------------------------------------------------
Status:         Failure
---------------------------------------------------------------------
```

The build is in failing state because the pack for **.NETFramework 4.5** could not be done on Linux but it will work well on Windows.

I tried to use `CSharp script files` but the `Csi` tool isn't available on Linux, FSharp is a concise language and it's pretty fun to use it :)

Please let me know if you have any question and if you want me to add the other projects as well.

**Comment by fedj** [comment]
@klettier Thanks a lot for this work! I think it's pretty easy to understand (even in F#).
Regarding the package target, we can make it optional in the compile run for the moment as it was not packaging with the current "tools". Can we still keep it to be able to run it manually ?

cc @crntn @gboucher90

**Comment by klettier** [comment]
Yes you can run it manually as well

You can pass any know target name to the script file and it will stop the pipeline to the one you provided. 

if you don't provide any it will execute the default one that is specified at the end of the script. 

You could even execute the script in fsharp interactive by selecting just the lines you want to execute. 

Beauty of FSharp :)

**Comment by klettier** [comment]
Is the proposition suit you ?

**Comment by fedj** [comment]
@klettier Sorry the misunderstanding. Yes, the proposition suits me perfectly

**Comment by klettier** [comment]
Nice, I'll finish the set-up ASAP
