### ISSUE TITLE
I'd like to use Zipkin from an ASP.NET application (non .NET Core)

### ISSUE THREAD

**Issue by zignd** [openzipkin/zipkin4net#145]
I'd like to use Zipkin from an ASP.NET application (not .NET Core). Is it possible? This library seems to support only ASP.NET Core. But if that's the case, is there any other I could use that would meet my needs?

Thanks in advance.

**Comment by crntn** [comment]
Hi @zignd, Zipkin4net does support .Net 4.5 !
Plus if you're using Owin there is a middleware here https://github.com/openzipkin/zipkin4net/tree/master/Src/zipkin4net.middleware.owin that was provided by @klettier. 
For an example on how to use it you can look here https://github.com/openzipkin/zipkin4net/tree/master/Examples/owin

**Comment by zignd** [comment]
Oh, that's great to know! Thanks, I'll try it out.

**Comment by fedj** [comment]
@zignd Did you get time to try ?

**Comment by zignd** [comment]
@fedj Yup, I tried the example and it worked very well. Thanks again! :)

**Comment by fedj** [comment]
Good to hear ! Don't hesitate if you have any question!
