### ISSUE TITLE
Add support for Message Broker type messages

### ISSUE THREAD

**Issue by aachinfiev** [openzipkin/zipkin4net#150]
Open Zipkin documentation defines ms/mr type of messages for cases with a publisher and one or more consumers of a given event. Unfortunately zipkin4net currently does not support sending these types of spans to the server. 

I have tested submitting a JSON request via v1/api/spans and Zipkin UI renders associated events. 

    [
        {
            "traceId": "f95ae2017821cb14",
            "id": "886a8994ecf8bf35",
            "name": "consumer1method",
            "timestamp": 1507247375925111,
            "annotations": [
                {
                    "timestamp": 1507247375925111,
                    "value": "mr",
                    "endpoint": {
                        "serviceName": "consumer1"
                    }
                }
            ],
            "binaryAnnotations": [
                {
                    "key": "ID",
                    "value": "76a5ef53-61c6-4043-8ee5-1f74fa2dd6b1",
                    "endpoint": {
                        "serviceName": "consumer1"
                    }
                }
            ]
        },
        {
            "traceId": "f95ae2017821cb14",
            "id": "87fd0e42c0cc0129",
            "name": "producerprocess",
            "parentId": "886a8994ecf8bf35",
            "timestamp": 1507247376027131,
            "annotations": [
                {
                    "timestamp": 1507247376027131,
                    "value": "ms",
                    "endpoint": {
                        "serviceName": "producer"
                    }
                }
            ]
        },
        {
            "traceId": "f95ae2017821cb14",
            "id": "8094558e4feeaf12",
            "name": "consumer2process",
            "parentId": "87fd0e42c0cc0129",
            "timestamp": 1507247376047135,
            "annotations": [
                {
                    "timestamp": 1507247376047135,
                    "value": "mr",
                    "endpoint": {
                        "serviceName": "consumer2"
                    }
                }
            ]
        }
    ]

It would be very helpful if this was added to the interface to support these types of events as there is a lot of distributed systems now that rely on pub/sub type of flows. Thank you.

**Comment by codefromthecrypt** [comment]
fyi this shows the flow which is optimized for zipkin v2 formatting and api
vs event model: http://zipkin.io/pages/instrumenting.html

here's the translation to events/annotations
https://github.com/openzipkin/zipkin-api/pull/29/files

**Comment by fedj** [comment]
Hi @aachinfiev,

Thank you for this issue, we'll definitely add this feature.
@adriancole From what I understand from https://github.com/openzipkin/zipkin/issues/1243#issuecomment-266359841, MS and MR should share the same span id and should MR should not be a child of MS. But if I take a look at https://github.com/openzipkin/zipkin-api/pull/29/files#diff-f2ea8769bf9ee8697409ed187e0f843bR84, it says otherwise.

Should MR be the child of MS ?

**Comment by codefromthecrypt** [comment]
Correct. We are basically leaving shared span as rpc only (not any other
remote thing). Also helps with messaging as you can more easily reason with
muliple consumers of a message.
