### ISSUE TITLE
IPV4 can't display on zipkin server

### ISSUE THREAD

**Issue by anthonywanted** [openzipkin/zipkin4net#165]
HI, I use zipkin4net 1.1.1 with the latest zipkin-server(storage type: es, collector: kafka-10)

I get zipkin like this
wget -O zipkin-server-exec.jar 'https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec'

I found that anything about endpoint ip address is not working

Zipkin4net send endpoint ip address in int format(confirmed in code and capture in kafka)
![qq 20171226153601](https://user-images.githubusercontent.com/26265122/34350582-850e5c12-ea52-11e7-8ed8-a2d5839dc67a.jpg)

    private static void SerializeEndPoint(StreamWriter writer, IPEndPoint endPoint, string serviceName)
    {
        writer.Write(openingBrace);
        writer.WriteField(ipv4, SerializerUtils.IpToInt(endPoint.Address));
        writer.Write(comma);
        writer.WriteField(port, (short)endPoint.Port);
        writer.Write(comma);
        writer.WriteField(JSONSpanSerializer.serviceName, SerializerUtils.ToEscaped(serviceName));
        writer.Write(closingBrace);
    }

But when I go to zipkin ui, I can't find the ip address
![image](https://user-images.githubusercontent.com/26265122/34350630-c3e1f412-ea52-11e7-8606-7525fd6b6200.png)

![image](https://user-images.githubusercontent.com/26265122/34350645-dcbb99c0-ea52-11e7-8f1f-cb0309bae18e.png)

When I change the zipkin4net SerializeEndPoint to this(ip address like '127.0.0.1'), it works fine

    private static void SerializeEndPoint(StreamWriter writer, IPEndPoint endPoint, string serviceName)
    {
        writer.Write(openingBrace);
        writer.WriteField(ipv4, endPoint.Address.ToString());
        writer.Write(comma);
        writer.WriteField(port, (short)endPoint.Port);
        writer.Write(comma);
        writer.WriteField(JSONSpanSerializer.serviceName, SerializerUtils.ToEscaped(serviceName));
        writer.Write(closingBrace);
    }

Is there any other way to fix this problem without changing the code of the zipkin4net?

**Comment by fedj** [comment]
Hi @anthonywanted,

Thanks for reporting this bug. It indeed seems like a bug. Your correction seems to fix the problem.
Would you be able to submit a PR ?

If you don't mind changing the serialization protocol, you can use thrift instead of JSON in the meantime if you can't wait for a version release.

**Comment by anthonywanted** [comment]
I will submit a PR soon. I can’t use the thrift serializer, may be something wrong with my usage.

**Comment by fedj** [comment]
Fixed in #182, thanks a lot for your help @anthonywanted !
