### ISSUE TITLE
Signing packages

### ISSUE THREAD

**Issue by klettier** [openzipkin/zipkin4net#183]
Hi,

Any possibility to sign all your packages to allow us to depend on them from signed libraries ? 

Thanks, 

Kévin

**Comment by fedj** [comment]
I don't see why not. I'll ask a few questions around me and get back to you

**Comment by bhugot** [comment]
Hello, any news on this?

**Comment by fedj** [comment]
Actually no, I must admit I don't have much knowledge about signed libraries.
We would need to get a certificate to sign though

**Comment by fedj** [comment]
@klettier you mean signing it with a pfx file ? If so, I'm not sure how to get one

**Comment by bgrainger** [comment]
I assume @klettier just means strong-naming. To do this, use `sn -k zipkin4net.snk`, then add `<SignAssembly>true</SignAssembly>` and `<AssemblyOriginatorKeyFile>`. For an example, see https://github.com/bgrainger/MySqlConnector/commit/814958c312bcd2c677a483bb4c39c50fec32da93.

**Comment by klettier** [comment]
Sorry for my late reply, yes just follow [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name)
