### ISSUE TITLE
run owin example

### ISSUE THREAD

**Issue by withlin** [openzipkin/zipkin4net#187]
would you help me? 
i run owin example. 
and then via  http://localhost:9411/?serviceName=backend 
which is nothing.
![run picture](https://user-images.githubusercontent.com/22409551/35959400-6ee96c64-0ce0-11e8-84ef-12fe66b658d0.png)

![zipkinServer](https://user-images.githubusercontent.com/22409551/35959441-9e503fd2-0ce0-11e8-90b9-d7efef102591.png)

so what can i do?

**Comment by fedj** [comment]
Hi @WithLin0510,

Sorry for the delay.
If I understand correctly, you're not seeing any trace in Zipkin. Did you try to open http://localhost:8081 first ?

Basically, frontend app calls backend app and both send a common trace to zipkin. Once a trace has been generated (by calling frontend), it should appear in zipkin's UI (localhost:9411)

**Comment by withlin** [comment]
oh, Thank U. i just run it success!

**Comment by fedj** [comment]
Glad it worked ! Also, don't hesitate to ask questions directly on [gitter](https://gitter.im/openzipkin/zipkin) to have more direct answers/feedback
