### ISSUE TITLE
Version 1.2.0 ZipkinTracer Error.

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin4net#205]
Hi,

I'm experiencing an error when using Zipkin4Net version 1.2.0,
Im trying to run it on WEBAPI Core 2.0 using the following code:

`            TraceManager.SamplingRate = 1.0f;
            var logger = new ZipkinLogger();
            JSONSpanSerializer jSONSpanSerializer = new JSONSpanSerializer();
            var httpSender = new HttpZipkinSender("http://localhost:9411", "application/json");
            var tracer = new ZipkinTracer(httpSender, jSONSpanSerializer);
            TraceManager.RegisterTracer(tracer);
            TraceManager.Start(logger);`

Its under ConfigurationServices in the Startup.
The error i'm receiving is as follows:

> System.ArgumentNullException occurred
  HResult=0x80004003
  **Message=You have to specify a non-null statistics.
  Source=zipkin4net**
  StackTrace:
   at zipkin4net.Tracers.Zipkin.ZipkinTracerReporter..ctor(IZipkinSender sender, ISpanSerializer spanSerializer, IStatistics statistics)
   at zipkin4net.Tracers.Zipkin.ZipkinTracer..ctor(IZipkinSender sender, ISpanSerializer spanSerializer, IStatistics statistics)
   at <MyProject>.Startup.ConfigureServices(IServiceCollection services) in C:\Projects\Startup.cs:line 53

The weird part is when i download the example Project and added reference to it from my Project the code ran Great without any errors,

Is it a version issue?

Best Regards,
Eitam.

**Comment by fedj** [comment]
Hi @eitamring,

It has been fixed here (https://github.com/openzipkin/zipkin4net/commit/a1e8c1b0a18374490871865a3adc8d0577b94501) but not released yet. As a workaround while waiting for the release, you can provide a Statistics object (by calling new Statistics) to ZipkinTracer constructor.

In the meantime, I'll release a new version 1.2.1 asap

**Comment by ghost** [comment]
Hi @fedj.

Great to hear ,
As for now i will use 1.1.1 to prevent code change later ,
Thank you for the quick response!

Should we keep this issue open until the new version?

**Comment by fedj** [comment]
Yes, I will close it after it's done to track it

**Comment by fedj** [comment]
https://www.nuget.org/packages/zipkin4net/1.2.1 published. Thanks for the issue !
