### ISSUE TITLE
Zipkin4net Example 

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin4net#207]
Hi,

Any running Example for zipkin?
im trying to send a requst but i cannot for the love of god understand how the injection work ...
This is what my program send:

`            string serviceName = "Name";

            var trace = Trace.Create();

            string rpc = "POST";
            trace.Record(Annotations.ClientSend());
            trace.Record(Annotations.ServiceName(serviceName));
            trace.Record(Annotations.Rpc(rpc));
            trace.Record(Annotations.Tag("test.callServiceUrl", "applicationName"));
            trace.Record(Annotations.Tag("test.applicationName", "applicationName"));
            trace.Record(Annotations.ClientRecv());
            Trace.Current = trace;
            trace = Trace.Current.Child();
            string a = "aa";
            client.BaseAddress = new Uri("http://localhost:XXXX/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Add("cache-control", "no-cache");
            client.DefaultRequestHeaders.Add("x-Name", "URL");
            client.DefaultRequestHeaders.Add("Accept-Language", "en-US");
            Console.WriteLine(client.DefaultRequestHeaders);
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "Authentication");
            var json = new { ParamName = 0, ParamName = XXX, ParamName = "s12345678" };
            request.Content = new StringContent(JsonConvert.SerializeObject(json).ToString(),
                                                Encoding.UTF8,
                                                "application/json");`

This is send request to the APi,
The side that receive the request got the following code:

```
          string serviceName = "API";
            IExtractor<IHeaderDictionary> traceExtractor = Propagations.B3String.Extractor((IHeaderDictionary carrier, string key) => string.Join(",", carrier[key]));
            var traceContext = traceExtractor.Extract(Request.Headers);
            var trace = traceContext == null ? Trace.Create() : Trace.CreateFromId(traceContext);

            Trace.Current = trace;
            string servisceName = "API";

            trace.Record(Annotations.ServerRecv());
            trace.Record(Annotations.ServiceName(serviceName));
            trace.Record(Annotations.Rpc("GET"));
            trace.Record(Annotations.Tag("test", " landau 112"));
```

Does anyone have an idea what im doing wrong?
I know i dont inject the trace , but to be honest i couldn't figure out how to.
I did implement the bootstrap on the startup file.

**Comment by fedj** [comment]
Hi @eitamring,

Did you already take a look at examples folder ? You can find [asp.net core example](https://github.com/openzipkin/zipkin4net/tree/master/Examples/aspnetcore) and[ owin example](https://github.com/openzipkin/zipkin4net/tree/master/Examples/owin).

From the code snippet you posted, I can see some errors:
- ClientRecv annotation is supposed to be added after the call to localhost:XXXX ends
- You need to inject headers exactly the same way you extract them. If you take a look at [asp.net core example](https://github.com/openzipkin/zipkin4net/blob/master/Examples/aspnetcore/frontend/Startup.cs), you can see it uses a [TracingHandler](https://github.com/openzipkin/zipkin4net/blob/96cd42665f7ec57b48f7dc9cd5746c1dbfa97906/Src/zipkin4net/Src/Transport/Http/TracingHandler.cs) object. You'll find the injection of headers in this class.

If you still struggle to make it work, don't hesitate to take a look at examples, find us on [gitter](https://gitter.im/openzipkin/zipkin) or continue on this issue

**Comment by ghost** [comment]
hi @fedj ,

I see ,
I already looked at Owin , but for some reason missed the handler,
i will try it tomorrow again, Thanks for the quick replay!

**Comment by fedj** [comment]
@eitamring Did you find the time to test ?

**Comment by ghost** [comment]
@fedj 
Hi Fedj , yes , sorry for not responding ,
Just checked it and it working great!

**Comment by fedj** [comment]
Glad to hear it, thanks a lot !
