### ISSUE TITLE
Allow for custom record dispatchers

### ISSUE THREAD

**Issue by cpx86** [openzipkin/zipkin4net#208]
Currently, there exists an IRecordDispatcher interface and internally, the record dispatcher is pluggable (e.g. there's a special dispatcher used for unit tests). Would it make sense to expose this as public?

My use case currently is that I'm looking into implementing a few instrumentation middlewares, and there's no good way to unit test them since the dispatch happens asynchronously. I could also imagine that it might be interesting for advanced users to be able to change the dispatcher, e.g. if you have a custom tracer that's writing to a non-HTTP transport then you might want to be able to fine-tune how the records get dispatched to the tracer.

**Comment by fedj** [comment]
@cpx86 Yes it would make perfect sense. Can you come with a PR ?

**Comment by fedj** [comment]
1.2.2 just released, thanks for this !
