### ISSUE TITLE
Zipkin Error Span

### ISSUE THREAD

**Issue by stvndall** [openzipkin/zipkin4net#212]
I haven't seen a way to be able to send a trace resulting in a red trace on Zipkin itself.

Am I missing something? If I'm correct, I'm looking for a way to send the error 

From MR https://github.com/openzipkin/zipkin/issues/1140

**Comment by codefromthecrypt** [comment]
a tag/ binary annotation named "error" will result in a red span.

**Comment by stvndall** [comment]
Sorted, thanks.
Might be useful (though not required) to expose something on the trace contract for errors. But I've got it turning red :smile:

**Comment by vikrambe** [comment]
@adriancole Can you share zipkin span model explaining significance of error span tag and how is it treated ?

**Comment by codefromthecrypt** [comment]
unfortunately, swagger (to best of my knowledge) and protobuf do not have a
way to define constants like thrift does. Here's the documentation for the
thrift def of that tag.

https://github.com/openzipkin/zipkin-api/blob/master/thrift/zipkinCore.thrift#L260

any value of the tag will color the span red in the UI and be counted as an
error in service dependency aggregation.
