### ISSUE TITLE
How does it work together with HttpClientFactory

### ISSUE THREAD

**Issue by senj** [openzipkin/zipkin4net#216]
Hi, when I try to add this Handler like this:
```
services.AddSingleton<TracingHandler>(new TracingHandler(ServiceName));
services.AddHttpClient("MyHttpClient", ConfigureMyHttpClient)
   .AddHttpMessageHandler<TracingHandler>();
```

I get error: 
```
DelegatingHandler instances provided to HttpMessageHandlerBuilder must not be reused or cached
```

**Comment by fedj** [comment]
Hey @senj,

Which version are you using? It should have been fixed with https://github.com/openzipkin/zipkin4net/pull/214 in version 1.2.3

**Comment by fedj** [comment]
Hi @senj,

Any news ?

**Comment by senj** [comment]
I had to use AddPrimaryHttpMessageHandler for it to work.

**Comment by wdolek** [comment]
@senj I believe you are getting this exception because you registered handler as singleton. So after first usage, inner handler stays set and that's why you get exception. Try to change your registration to:

```
services.AddTransient(_ => TracingHandler.WithoutInnerHandler("ServiceName"));
```

**Comment by dzejsien** [comment]
I used it like that: 
.AddHttpMessageHandler(_ => TracingHandler.WithoutInnerHandler("serviceName"))

**Comment by venkatr21** [comment]
@dzejsien I am facing the same issue. 
.AddHttpMessageHandler(_ => TracingHandler.WithoutInnerHandler("serviceName")) did this solve the issue?
Were you able to find other alternatives / best practices for this?
