### ISSUE TITLE
I'd like to use Zipkin from an ASP.NET application (non .NET Core and non Owin)

### ISSUE THREAD

**Issue by jsgaoshang** [openzipkin/zipkin4net#219]
I'd like to use Zipkin from an ASP.NET application (not .NET Core and not Owin). For example .NET Framework 4.6.1 webApi ,Is it possible? This library seems to support only ASP.NET Core and Owin. But if that's the case, is there any other I could use that would meet my needs?

Thanks in advance.

**Comment by fedj** [comment]
Hi @jsgaoshang,

We don't provide any support for Asp.Net (not core) as we didn't have the need yet. Would you be able to come with a PR ?

**Comment by jsgaoshang** [comment]
ok, I know, thank you！
