### ISSUE TITLE
TracingHandler does not give Server it's own SpanId

### ISSUE THREAD

**Issue by svantreeck** [openzipkin/zipkin4net#53]
I was looking at some of my traces and got similar results to @adriancole's results in #38 where the Client Send/Receive and Server Receive/Send are on the same span.  From looking at some of the other implementations, I think that the [javascript](https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-instrumentation-request/src/wrapRequest.js#L5) implementation is passing a new span to the service, and was thinking we should do the same.

![Trace](https://cloud.githubusercontent.com/assets/64215/24347372/aebc403a-130a-11e7-82c7-be1c8cbe4c77.png)

**Comment by codefromthecrypt** [comment]
so the normal case of tracing in zipkin is that the client originates a
trace which is then propagated and used on the server. another downstream
request would repeat this, but as a child span of the incoming one.

Main thing here is to make sure we have tests to show that the behavior is
like this, as it will ensure any fix (and also show there was a problem!)

**Comment by svantreeck** [comment]
I've got a scenario that I'm trying to add this to and I want to make sure that I'm tracing it correctly, and then we can adapt/test the library accordingly.  In my scenario, I have 3 Apis (we'll call them Api A, B, and C).  Each Api produces messages, and there are potentially multiple consumers that will take the published message and call an Api based on what happened.

This is the structure I think the traces should be in (parent:child relationship being the nesting here)
* `{TraceId: 1, SpanId: 2, ParentId: null}:` Api A gets called and makes a Server Receive/Server Send trace. 
  * `{TraceId: 1, SpandId: 3, ParentId: 2}:` Api A makes a Client Send/Client Receive trace when it publishes a message.  (Should this be a local operation instead of client?)
    * `{TraceId: 1, SpandId: 4, ParentId: 3}:` Consumer A->B has a Server Receive/Send trace when it consumes the message Api A produced
      *  `{TraceId: 1, SpandId: 5, ParentId: 4}:` Consumer creates a Client Send/Receive trace for calling Api B.  
         *  `{TraceId: 1, SpandId: 6, ParentId: 5}:` Api B has a Server Receive/Send trace.  
    * `{TraceId: 1, SpandId: 7, ParentId: 3}:` Consumer A->C has a Server Receive/Send trace when it consumes the message Api A produced.  
      *  `{TraceId: 1, SpandId: 8, ParentId: 7}:` Consumer A->C creates a Client Send/Receive trace for calling Api C.  
         *  `{TraceId: 1, SpandId: 9, ParentId: 8}:` Api C has a Server Receive/Send trace.  

Currently what I'm seeing is that my Consumer->Api traces get merged together into a single trace, so I'll see a trace like below that I don't think is correct:
`{TraceId: 1, SpandId: 8, ParentId: 7}:` Consumer A->C creates a Client Send/Receive trace for calling Api C.  Api C adds its Server Receive/Send annotations to the same span/trace.

**Comment by codefromthecrypt** [comment]
Interesting so you are trying for single producer multiple consumer..

B3 wasnt made for this as it assumes the trace/span/parent are shared on
receive side. You cant do that with multiconsumer bc the span would end up
confused. What it sounds like you want is to fork a span on receipt which
means each consumer has a different span id. Correct?

**Comment by fedj** [comment]
I agree with @adriancole, in the actual model, a span is originated by the client and represent the whole RPC (CS-SR-SS-CR annotations). Furthermore, I think this is an unsolved case of clock skew if your "server span" is a child of your "client span".
What are you trying to achieve ?

**Comment by svantreeck** [comment]
OK, I think I misunderstood the idea of client/server traces.

I was thinking that my client traces would give me an indication of the internal activity of a server trace, so if I had an api, I might break down caching, data access, etc all as their own client traces to trace the internal workings of the Api.  I was thinking that my visualization would look something like this with caching and a webservice call instead of having the client trace and server trace for ApiB combined:

```
Api A  |---------- Server Trace ----------|
Api A   |-- caching --|
Api A                  |--- call ApiB ---|
Api B                   |- Server Trace-|
```

All that said, I guess it makes sense to merge the two because it cleans up clutter on the visualization by having it appear as below instead.
```
Api A  |---------- Server Trace ----------|
Api A   |-- caching --|
Api B                  |--- call ApiB ---|
```

Assuming that the bottom scenario is correct, I'd be happy to close the issue/PR with the understanding of how the behavior is supposed to work.

**Comment by fedj** [comment]
If we take a real example like ![this one](http://4.bp.blogspot.com/-b0r71ZbJdmA/T9DYhbE0uXI/AAAAAAAAABs/bXwyM76Iddc/s1600/web-screenshot.png), I think it will be easier to communicate.

I suppose that WEB_CLUSTER service is calling WEB_SERVER service. When you visualize with your eyes the WEB_SERVER duration (which is here 109.358ms), you're seeing an RPC span composed of CS-SR-SS-CR annotations. All these annotations share the same (spanId=X, parentSpanId=1, traceId=1). 

WEB_SERVER itself calls immediatly "SOME SERVICE". "SOME_SERVICE" is composed of cs-sr-ss-cr and all these annotations share the same (spanId=2, parentSpanId=X, traceId=1). Note that the parentSpanId is the value of WEB_SERVICE span id.

The same applies for the memcached called by WEB_SERVER. The span is only composed of cs-cr (because the server is not instrumented) and the parentSpanid = X.

Is that what you meant ?

**Comment by svantreeck** [comment]
That makes sense, thanks for the info guys!
