### ISSUE TITLE
TracingHandler should be extracted from middleware project

### ISSUE THREAD

**Issue by fedj** [openzipkin/zipkin4net#76]
TracingHandler doesn't have a dependency on asp.net core and it's sad to depend on asp.net core when you only want the tracing handler.
It should be moved out of middleware

**Comment by klettier** [comment]
And [TracingLogger](https://github.com/criteo/zipkin4net/blob/master/zipkin4net-aspnetcore/Criteo.Profiling.Tracing.Middleware/TracingLogger.cs) too.

**Comment by fedj** [comment]
TracingLogger is bound to Microsoft.Extensions.Logging, thus adding a dependency in zipkin4net.
