### ISSUE TITLE
how to run this zipkin example 

### ISSUE THREAD

**Issue by byeswanth** [openzipkin/zipkin4net#77]
can some one please help me how to run the example which was given

**Comment by fedj** [comment]
Hi @byeswanth,

I'm not sure to understand which example you are referring to. If you're talking about an example with zipkin4net, you can find a step by step instruction manual [here](https://github.com/criteo/zipkin4net/tree/master/zipkin4net-example)

**Comment by fedj** [comment]
@byeswanth Did it answer your question ?

**Comment by byeswanth** [comment]
thank you very much @fedj for your early reply . can you tell me how to pass the span id and trace id along with the http request .

i.e., how to pass the span object created at the client side to the server side .

**Comment by fedj** [comment]
You can have a look at https://github.com/criteo/zipkin4net#b3-headers-propagation
[ZipkinHttpInjector](https://github.com/criteo/zipkin4net/blob/master/zipkin4net/Criteo.Profiling.Tracing/Transport/ZipkinHttpTraceInjector.cs) allows you to inject a trace to a carrier (http headers basically) while the [ZipkingHttpTraceExtractor](https://github.com/criteo/zipkin4net/blob/master/zipkin4net/Criteo.Profiling.Tracing/Transport/ZipkinHttpTraceExtractor.cs) allows you to extract the trace from headers.
