### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by senj** [openzipkin/zipkin4net#81]
Hey guys,
I think your product here is great, but it's really hard getting started.

Can you explain what's the difference between Client and Server Trace?

**Comment by fedj** [comment]
Hi @senj,

ClientTrace and ServerTrace were introduced recently and there's no documentation yet.
I'll update the readme but in the meantime, ClientTrace is meant for a client doing a request on a server and ServerTrace is the server part when it receives a request

**Comment by senj** [comment]
In a microservice world it's hard to tell who is the client and who is the server.. I used ClientTrace everywhere right now because it creates a nice hierarchy.. I think the middleware sets the correct ServerTrace anyway.

**Comment by fedj** [comment]
When we talk about the client, we mean the service issuing a request and by server we mean the service receiving a request. A service can typically be a client and a server at the same time.

Example:
Three services A, B and C

A -> B -> C

A calls B which calls C

A emits a ClientTrace when sending a request to B
B emits a ServerTrace when receiving a request from A
B emits a ClientTrace when sending a request to C
C emits a ServerTrace when receiving a request from B

**Comment by GadgetGeekUK** [comment]
The readme really doesn't help with getting started, even the included examples don't help. Having never used Zipkin before, there really should be documented prerequisites, .net core setup and example tracing.
It's not even clear what nuget packages to add to a project. Are they added at the API level, or the Web client itself? Does this send to the Zipkin Java/Docker server? Where is this configured?
