### ISSUE TITLE
Support .Net Standard 1.5

### ISSUE THREAD

**Issue by adamrodger** [openzipkin/zipkin4net#84]
The current NuGet package supports .Net Framework 4.5.1 and .Net Standard 1.6. However, this makes it cumbersome to use when creating your own cross-platform libraries which are intended for use on the full .Net Framework (any version) when using zipkin4net as a dependency because it forces them to also use .Net Standard 1.6 as a minimum.

The [.Net Standard Version Matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) shows that .Net Framework 4.6.2 only supports .Net Standard 1.5 without installing some pre-release tooling. That forces you to use multiple targeting in your own library when it shouldn't really be necessary.

I've had a look at the dependencies of zipkin4net and it should be possible to support .Net Standard 1.5 and therefore not need to use multiple targeting. The dependency on `apache-thrift-netcore` means the minimum needs to be 1.5, but nothing is forcing 1.6.

Could this change be made to make it easier to consume this package in .Net Standard libraries intended for both .Net Framework and .Net Core so that they only have to use .Net Standard 1.5 please?

**Comment by fedj** [comment]
Actually, zipkin4net uses v4.5 directly and not v4.5.1. v4.5.1 is only used for the asp.net core part. I see nothing preventing this change. Would you be able to make a PR ?

**Comment by adamrodger** [comment]
I've raised a PR for this. It's only a tiny change. Everything still
builds, all the tests pass and I built a sample NuGet locally to make sure
it looks OK.

**Comment by fedj** [comment]
It has been merged already, I'll come up with a nuget probably today

**Comment by fedj** [comment]
Sorry I was OOO, nuget was finally released
