### ISSUE TITLE
Http IZipkinSender example

### ISSUE THREAD

**Issue by Rurouni** [openzipkin/zipkin4net#9]
I couldn't find any example of how would one use this library without kafka, if you just want to report spans directly to Zipkin. 
How hard would be to implement one?

**Comment by fedj** [comment]
Hi @Rurouni,

It doesn't exist yet but I imagine it would just be a POST request on /spans route of your zipkin collector (according to http://zipkin.io/zipkin-api/#/paths/%252Fspans).

I can come up with a draft version if you wish.

**Comment by Rurouni** [comment]
After looking at how it's implemented at https://github.com/clearctvm/zipkin.net it seems you need to do POST to` /api/v1/spans` with `ContentType: application/x-thrift` so it is straightforward indeed, but requires initial digging, so I think that having Http option included out of the box would help with adoption of this library

**Comment by fedj** [comment]
We just added an HttpZipkinSender. You're totally right when saying it'll help with adoption (not only the lib but also with Zipkin itself as the collector http is basically the first step to test now). Thanks for your feedback
