### ISSUE TITLE
Build for .NET 4.5 does not work, fails to find/restore packages

### ISSUE THREAD

**Issue by aliostad** [openzipkin/zipkin4net#94]
To reproduce:

 - git clone
 - open zipkin4net.sln in Visual Studio (2017)
 - build

I see `packages.config` files but they are not part of the solution. I added them to get around the build issue but for some reason does not work.

**Comment by aliostad** [comment]
OK, this is fixed in my new PR.

**Comment by aliostad** [comment]
OK, I am re-opening this for coordination. Can you please respond here rather than in the mother thread.

As I said before, you need to let me know whether pursue fixing this myself or it is something you will be doing your end and whether you need my help.

**Comment by fedj** [comment]
@aliostad Thanks for reporting this issue. I'm currently working on a solution where net45 is available for 2017 csproj but travis will still compile netstandard until we find a solution.
Nuget can therefore be published supporting net45 and netstandard

**Comment by fedj** [comment]
@aliostad It works on my VS2017 with this fix. Can you test ?

**Comment by aliostad** [comment]
What I care about most is command line build and having nuget. Does it work on those?

**Comment by aliostad** [comment]
I can see you closed this issue. 

I checked and build works but does not create 4.5 binaries. The PR I sent was generating them. Am I missing something?

**Comment by fedj** [comment]
@aliostad The PR allows to generate a nuget with both net standard and net45 supported. I will release a new nuget tomorrow as I don't have a windows machine at home. Isn't that what you needed ?

The PR you sent didn't have a green build due to some incompatibilities with linux for now. I guess we can't say your PR was generating them then.

What about creating a PR creating a script for windows ?

**Comment by fedj** [comment]
Nuget published with [version 0.4.1](https://www.nuget.org/packages/Criteo.Profiling.Tracing/0.4.1)

**Comment by aliostad** [comment]
Thanks a lot. 
Fine with that PR, my point was that if you want to pick some of that work.
Yeah, I can work on a command line build for windows and .NET 4.5. I will create an issue.

Cheers

**Comment by fedj** [comment]
Please come back to us if you need anything related to this issue.
