### ISSUE TITLE
Criteo.Profiling.Tracing 0.4.1 should be a 1 to 32 character lower-hex string with no prefix

### ISSUE THREAD

**Issue by mypjb** [openzipkin/zipkin4net#99]
I am using the latest zipkin driver, and the error error of sending the trace id is that：should be a 1 to 32 character lower - hex string with no prefix
I opened the TraceManager.Trace128Bits

**Comment by codefromthecrypt** [comment]
Did you get this error from Zipkin itself (presumably from json sent to the
POST /api/v1/spans endpoiny)? Or on a java service your .net called (and
broke reading X-B3-TraceId)?

**Comment by mypjb** [comment]
Error from zipkin itself.

**Comment by codefromthecrypt** [comment]
that message is coming from this code:

```java
  static NumberFormatException isntLowerHexLong(String lowerHex) {
    throw new NumberFormatException(
        lowerHex + " should be a 1 to 32 character lower-hex string with no prefix");
  }
```

The trace ID should be prefixed to the message.. if it wasn't, it hints at an empty trace ID?

**Comment by codefromthecrypt** [comment]
yeah... I just made json with `"traceId": ""` and got this error:

```
Caused by: java.lang.NumberFormatException:  should be a 1 to 32 character lower-hex string with no prefix
```

I suppose we could change the error to say that the trace ID was empty as it is less confusing than the above. At any rate, if indeed empty traceId was passed, we'd need to look closely here how that could be possible.

**Comment by fedj** [comment]
@mypjb Thanks for reporting the issue.

I'm pretty concerned since we shouldn't send a trace that has no trace Id.
Can you send an example/snippet of code to check what's happening ?

**Comment by crntn** [comment]
I think that in the case of @mypjb the exception comes from the fact that traceId is not lower case (cf #103 ), assuming JSONSpanSerializer was used.

@adriancole  I agree that having 2 distinct errors between empty string and uppercase traceId would help with debugging.

**Comment by codefromthecrypt** [comment]
good catch. will fix the error message tomorrow!

**Comment by fedj** [comment]
@mypjb Would you be able to test again with patch #103 ?

**Comment by codefromthecrypt** [comment]
couldn't repro the problem, but anyway tests are in now to make sure
https://github.com/openzipkin/zipkin/commit/322ee2f96f026031b57375f04bf356fbe0cde56c

**Comment by crntn** [comment]
Thanks Adrian !

@mypjb release 0.4.2 should fix your issue, https://www.nuget.org/packages/Criteo.Profiling.Tracing/0.4.2
